### ISSUE TITLE
[FEATURE] <deploy-key>

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/enac-cd-app#6]
If 'app_repo="git@github.com:EPFL-ENAC/unhcr-geneva-tech-hub-app.git". in an inventory uses git (ssh protocol) instead of https. 
We won't be able to deploy using the api because the we probably don't have the deploy key of the repository

example:
https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/actions/runs/4913298114/jobs/8773327998

# problem
we can switch to https for public repository; but for private repository it won't be possible to deploy.

# Do we do something?

Is it the expected behavior ? For instance resslab-hub is a private repo... https://github.com/RESSLab-Team/resslab-hub

**Comment by sbancal** [comment]
As discussed, we don't have problem with ssh+git.
